# -*- coding: utf-8 -*-
"""报告数据：目录/文件中文说明（供 gen_report*.py 使用）。"""
import json

INV_B = json.load(open("/home/user/Yuxi/analysis/inventory_backend.json", encoding="utf-8"))
INV_F = json.load(open("/home/user/Yuxi/analysis/inventory_frontend.json", encoding="utf-8"))

def esc(s):
    import html
    return html.escape(str(s), quote=False)

DIR_DESCR_B = {
 "backend/server": "【HTTP 入口层】FastAPI Web 应用与全部 API 路由，只做请求/响应适配，业务逻辑都转发给 yuxi 包。",
 "backend/server/routers": "26 个路由文件，按业务域拆分，全部在 __init__.py 集中注册到 /api 前缀。",
 "backend/server/utils": "服务启动生命周期(lifespan)、认证依赖、访问日志、知识库权限等 Web 层工具。",
 "backend/package/yuxi": "【业务主体包】所有领域逻辑、数据访问、存储适配都在这里。",
 "backend/package/yuxi/agents": "【智能体体系】基于 LangGraph/LangChain 的智能体定义：基类、上下文、内置智能体、中间件、工具箱、Skills、MCP。",
 "backend/package/yuxi/agents/backends": "智能体的文件系统后端：把用户工作区/沙盒/知识库映射成智能体可读写的文件系统。",
 "backend/package/yuxi/agents/backends/sandbox": "沙盒后端：通过 sandbox-provisioner 提供隔离的命令执行与文件环境。",
 "backend/package/yuxi/agents/buildin": "内置智能体后端注册表（BUILTIN_BACKENDS）：ChatbotAgent 与 SubAgentBackend。",
 "backend/package/yuxi/agents/buildin/chatbot": "默认『智能助手』：LangGraph 图、提示词、状态、可配置项。",
 "backend/package/yuxi/agents/buildin/subagent": "内置子智能体后端：受限工具集的执行图。",
 "backend/package/yuxi/agents/callbacks": "模型调用过程的回调（计时等观测）。",
 "backend/package/yuxi/agents/mcp": "MCP（Model Context Protocol）服务管理与内置 MCP 注册。",
 "backend/package/yuxi/agents/middlewares": "智能体中间件：文件系统、Skills、记忆、子任务、摘要、网络重试、审批、Token 统计等，像『洋葱』一样包在模型外面。",
 "backend/package/yuxi/agents/presets": "预置角色定义（deep_research 深度研究、默认助手、多个子智能体角色）。",
 "backend/package/yuxi/agents/presets/subagents": "预置子智能体角色：事实核查、通用、调研探索、联网搜索。",
 "backend/package/yuxi/agents/skills": "Skills 管理：仓库存取、运行时只读投影、远程 Skill 安装（一次性沙盒执行）。",
 "backend/package/yuxi/agents/skills/buildin": "内置 Skill 包（如 mysql-reporter MySQL 报表）。",
 "backend/package/yuxi/agents/skills/buildin/mysql-reporter/scripts": "内置 MySQL 报表 Skill 的命令行脚本。",
 "backend/package/yuxi/agents/toolkits": "工具箱：工具注册表、按配置解析运行时工具。",
 "backend/package/yuxi/agents/toolkits/buildin": "内置工具：联网搜索、OCR、产物暴露(artifacts)、追问用户、安装 Skill。",
 "backend/package/yuxi/agents/toolkits/debug": "调试工具。",
 "backend/package/yuxi/agents/toolkits/kbs": "知识库工具：列出/检索/打开/预览知识库文档，供智能体在对话中调用。",
 "backend/package/yuxi/config": "系统级路径与环境配置：用户数据目录、Skill 目录、运行时目录。",
 "backend/package/yuxi/knowledge": "【知识库领域】知识库抽象、工厂、管理器、文档解析(OCR)、分块、向量实现(Milvus/Dify/Notion)、图谱、评估、预览。",
 "backend/package/yuxi/knowledge/chunking": "文档分块策略入口。",
 "backend/package/yuxi/knowledge/chunking/ragflow_like": "类 RAGFlow 的分块实现：dispatcher 按配置分发到具体解析器。",
 "backend/package/yuxi/knowledge/chunking/ragflow_like/parsers": "多种分块解析器：书籍/通用/法律法规/QA/语义/分隔符。",
 "backend/package/yuxi/knowledge/chunking/ragflow_like/utils": "分块辅助：Markdown 解析、中英文分句、表格转换。",
 "backend/package/yuxi/knowledge/eval": "RAG 评估：评测数据集生成、评估器、评估服务。",
 "backend/package/yuxi/knowledge/graphs": "知识图谱：Milvus 图服务、图向量库、LLM 实体抽取器。",
 "backend/package/yuxi/knowledge/graphs/extractors": "图实体抽取器（LLM 抽取）。",
 "backend/package/yuxi/knowledge/implementations": "知识库具体实现：Milvus 向量库、Dify、Notion、只读连接器。",
 "backend/package/yuxi/knowledge/parser": "文档解析器：MinerU、PaddleOCR、RapidOCR、DeepSeek OCR、统一入口、ZIP 处理。",
 "backend/package/yuxi/knowledge/utils": "知识域工具：参数处理、URL 抓取。",
 "backend/package/yuxi/models": "模型适配层：对话模型(chat)、向量模型(embed)、重排模型(rerank)的加载与调用。",
 "backend/package/yuxi/models/providers": "模型供应商管理：Provider 定义持久化到 PostgreSQL，经 Redis 缓存提供一致视图。",
 "backend/package/yuxi/permissions": "权限定义。",
 "backend/package/yuxi/repositories": "【数据访问层】PostgreSQL 访问边界：23 个 Repository，每个业务对象一个文件。",
 "backend/package/yuxi/services": "【用例层】43 个服务文件：一次业务动作的编排都从这里开始（发消息、排队、执行 Run、知识库任务……）。",
 "backend/package/yuxi/storage": "存储适配：postgres / redis / minio / neo4j。",
 "backend/package/yuxi/storage/minio": "MinIO 对象存储：上传、下载、临时文件访问。",
 "backend/package/yuxi/storage/neo4j": "Neo4j 图数据库驱动共享管理。",
 "backend/package/yuxi/storage/postgres": "SQLAlchemy 模型（业务表 + 知识表）与连接池管理。",
 "backend/package/yuxi/storage/redis": "Redis 客户端（同步/异步）与 ARQ 连接参数。",
 "backend/package/yuxi/storage_migrations": "数据库 Schema 迁移脚本（由 storage-migrator 容器执行）。",
 "backend/package/yuxi/utils": "跨领域通用工具：认证、日志、时间、SSE、文件预览、安全文件原语。",
 "backend/package/yuxi/workspace": "用户工作区：uid 路径映射、no-follow 安全文件原语、Workdir 视图、文件预览。",
 "backend/scripts": "辅助脚本（初始化种子用户等）。",
}

FILE_DESCR_B = {
 "backend/server/main.py": "FastAPI 应用入口：创建 app、挂载全部 /api 路由、CORS、访问日志与登录限流中间件；python -m server.main 启动 API 服务(5050 端口)。",
 "backend/server/worker_main.py": "ARQ 后台进程入口：加载 WorkerSettings 并调用 run_worker 启动任务执行器。",
 "backend/server/routers/__init__.py": "路由注册中心：把 26 个业务路由按顺序统一挂载到 /api 前缀。",
 "backend/server/routers/agent_router.py": "智能体主路由：智能体增删改查、POST /api/agent/runs 发起对话、排队查询/取消/steer、Run 状态/结果/事件 SSE、取消 Run。",
 "backend/server/routers/agent_invocation_call_router.py": "Agent Call 路由：外部程序以同步/异步方式调用智能体。",
 "backend/server/routers/agent_invocation_channel_router.py": "Agent 调用通道路由：管理外部调用通道。",
 "backend/server/routers/agent_invocation_eval_router.py": "Agent 调用评测路由。",
 "backend/server/routers/auth_router.py": "认证路由：POST /api/auth/token 登录换 JWT、注册、用户信息、OIDC 单点登录、CLI 浏览器授权、改密、管理员管理用户。",
 "backend/server/routers/auth_dept_router.py": "部门管理路由：部门与权限数据。",
 "backend/server/routers/chat_router.py": "会话路由：线程创建/列表/删除/搜索、消息历史、图片与附件上传、消息反馈。",
 "backend/server/routers/dashboard_router.py": "仪表盘路由：管理员统计聚合数据。",
 "backend/server/routers/external_kb_router.py": "外部知识库只读检索路由：供 CLI 与外部 Agent 调用。",
 "backend/server/routers/filesystem_router.py": "工作台文件系统视图路由：浏览 Agent 工作区文件（viewer）。",
 "backend/server/routers/graph_router.py": "知识图谱查询路由：全图/子图/标签/统计。",
 "backend/server/routers/knowledge_dashboard_router.py": "知识域仪表盘统计路由。",
 "backend/server/routers/knowledge_eval_router.py": "知识库评估路由：生成评测数据集、运行评估。",
 "backend/server/routers/knowledge_router.py": "知识库管理主路由（最大的路由文件）：知识库 CRUD、文档上传/解析/入库/检索、图谱构建、思维导图、导出。",
 "backend/server/routers/mcp_router.py": "MCP 服务管理路由：注册/编辑/启停 MCP Server、环境变量。",
 "backend/server/routers/mention_router.py": "@ 提及路由：聊天输入框 @ 文件时的搜索接口。",
 "backend/server/routers/model_provider_router.py": "模型供应商管理路由：管理员配置各 Provider 与模型列表。",
 "backend/server/routers/project_router.py": "项目路由：创建/选择/重命名项目。",
 "backend/server/routers/scheduled_agent_router.py": "定时智能体路由：用户自建定时任务 CRUD 与手动触发。",
 "backend/server/routers/skill_router.py": "Skills 路由：系统级 Skill 管理 + 用户可用 Skill 列表。",
 "backend/server/routers/system_router.py": "系统路由：健康检查、版本、系统配置项读写。",
 "backend/server/routers/system_task_router.py": "后台任务路由：任务列表/详情/取消/删除。",
 "backend/server/routers/tool_router.py": "工具路由：列出可用工具及其配置项。",
 "backend/server/routers/user_router.py": "用户路由：用户级配置与凭据管理。",
 "backend/server/routers/workspace_router.py": "个人工作区路由：文件树、读写文件、建目录 + 工作区知识文件只读视图。",
 "backend/server/utils/auth_middleware.py": "认证依赖：get_current_user 解析 Bearer JWT 或 X-API-Key，get_required_user / get_admin_user / get_superadmin_user 提供三级权限门槛。",
 "backend/server/utils/common_utils.py": "setup_logging()：日志初始化。",
 "backend/server/utils/access_log_middleware.py": "访问日志中间件：记录每个 HTTP 请求的处理耗时。",
 "backend/server/utils/lifespan.py": "API 启动/关闭生命周期：按顺序初始化安全密钥→数据库(校验 Schema)→系统配置→内置 MCP→内置 Skills→默认 Agent→模型供应商→知识库→Redis→沙盒→LangGraph checkpointer。",
 "backend/server/utils/knowledge_permissions.py": "知识库读/管理权限依赖（require_knowledge_base_read/manage）。",
 "backend/server/utils/knowledge_response.py": "知识库接口统一响应辅助。",
 "backend/package/yuxi/__init__.py": "yuxi 包入口：get_version() 提供版本号。",
 "backend/package/yuxi/main.py": "包级占位入口。",
 "backend/package/yuxi/storage_migration.py": "一次性历史存储切换迁移。",
 "backend/package/yuxi/agents/__init__.py": "agents 包入口：导出 BaseAgent 等公共符号。",
 "backend/package/yuxi/agents/base.py": "BaseAgent 智能体基类：get_graph() 抽象构图、stream_messages_with_state() 流式执行（内部走 LangGraph astream_events）、invoke_messages() 同步调用、每次构图独享 checkpointer。",
 "backend/package/yuxi/agents/context.py": "BaseContext 运行上下文基类：模型/工具/Skills/SubAgent 等可配置项 schema；filter_declared_config 过滤未声明字段。",
 "backend/package/yuxi/agents/state.py": "Agent 状态定义辅助。",
 "backend/package/yuxi/agents/tool_approval.py": "工具审批：normalize_tool_approval_mode 规范审批模式；create_tool_approval_middleware 生成人工审批/追问中间件。",
 "backend/package/yuxi/agents/buildin/__init__.py": "内置智能体后端注册表：BUILTIN_BACKENDS 显式注册、get_agent_backend/list_agent_backend_info 按需创建无共享状态的后端。",
 "backend/package/yuxi/agents/buildin/chatbot/graph.py": "默认『智能助手』ChatbotAgent：get_graph() 用 langchain create_agent 组装 模型+工具+提示词+中间件栈；_build_middlewares() 决定智能体拥有哪些能力。",
 "backend/package/yuxi/agents/buildin/chatbot/context.py": "ChatBotContext：智能助手的可配置项定义。",
 "backend/package/yuxi/agents/buildin/chatbot/prompt.py": "智能助手系统提示词构建 build_prompt_with_context()。",
 "backend/package/yuxi/agents/buildin/chatbot/state.py": "ChatBotState：智能助手 LangGraph 状态 schema。",
 "backend/package/yuxi/agents/buildin/subagent/graph.py": "内置子智能体后端 SubAgentBackend：带工具过滤中间件的受限执行图。",
 "backend/package/yuxi/agents/buildin/subagent/context.py": "SubAgentContext：子智能体上下文。",
 "backend/package/yuxi/agents/backends/composite.py": "YuxiFilesystemMiddleware + CompositeBackend：智能体文件系统后端，对超大工具输出做预算控制后再进入模型上下文。",
 "backend/package/yuxi/agents/backends/knowledge_base_backend.py": "知识库文件系统后端：把可见知识库文件以只读方式暴露给智能体。",
 "backend/package/yuxi/agents/backends/paths.py": "runtime 路径映射：把宿主 Workdir 映射为智能体视角的 /home/gem/... 路径。",
 "backend/package/yuxi/agents/backends/sandbox/backend.py": "ProvisionerSandboxBackend：命令执行走沙盒的文件系统后端。",
 "backend/package/yuxi/agents/backends/sandbox/download.py": "download_sandbox_directory：把沙盒目录打包下载。",
 "backend/package/yuxi/agents/backends/sandbox/provider.py": "SandboxConnection/Provider：与 sandbox-provisioner 的连接、挂载身份校验与惰性创建。",
 "backend/package/yuxi/agents/backends/sandbox/provisioner_client.py": "ProvisionerClient：sandbox-provisioner 的 HTTP 客户端。",
 "backend/package/yuxi/agents/mcp/service.py": "MCP 服务：ensure_builtin_mcp_servers_in_db 初始化内置 MCP；运行时加载 MCP 工具。",
 "backend/package/yuxi/agents/mcp/builtin.py": "内置 MCP Server 定义。",
 "backend/package/yuxi/agents/middlewares/context.py": "通用 Context 中间件（动态提示词注入）。",
 "backend/package/yuxi/agents/middlewares/dynamic_tool.py": "DynamicToolMiddleware：MCP 工具的动态加载与注册。",
 "backend/package/yuxi/agents/middlewares/memory.py": "用户级长期 Memory：提示注入 + 受限记忆工具。",
 "backend/package/yuxi/agents/middlewares/model_input.py": "ImageInputCompatibilityMiddleware：图片输入兼容桥接（OpenAI 工具图片格式转换）。",
 "backend/package/yuxi/agents/middlewares/network_retry.py": "NetworkRetryMiddleware：网络类错误按指数退避持续重试（总预算内），非网络错误按次数重试。",
 "backend/package/yuxi/agents/middlewares/skills.py": "SkillsMiddleware：Skills 提示词注入、依赖展开、动态激活。",
 "backend/package/yuxi/agents/middlewares/steer.py": "SteerMiddleware：主会话运行中接受用户『转向』新指令。",
 "backend/package/yuxi/agents/middlewares/subagent_task.py": "YuxiSubAgentMiddleware：提供 subagent_start / subagent_await 工具，负责子任务派发与等待。",
 "backend/package/yuxi/agents/middlewares/summary.py": "会话摘要中间件：长对话自动压缩为摘要，控制上下文长度。",
 "backend/package/yuxi/agents/middlewares/token_usage.py": "TokenUsageMiddleware：每次模型调用后统计 token 用量，按模型分桶累计到 Run/Thread 两级。",
 "backend/package/yuxi/agents/presets/deep_research.py": "深度研究预置角色定义。",
 "backend/package/yuxi/agents/presets/default_chatbot.py": "默认智能助手预置定义。",
 "backend/package/yuxi/agents/presets/subagents/fact_verifier.py": "预置子智能体：事实核查员。",
 "backend/package/yuxi/agents/presets/subagents/general_purpose.py": "预置子智能体：通用助手。",
 "backend/package/yuxi/agents/presets/subagents/research_explorer.py": "预置子智能体：调研探索员。",
 "backend/package/yuxi/agents/presets/subagents/web_search.py": "预置子智能体：联网搜索员。",
 "backend/package/yuxi/agents/skills/service.py": "Skill 服务：ResolvedSkill 解析用户最终可用的 Skill 及真实来源；init_builtin_skills 安装内置 Skill。",
 "backend/package/yuxi/agents/skills/repository.py": "SkillRepository：Skill 定义在 PostgreSQL 中的存取。",
 "backend/package/yuxi/agents/skills/runtime.py": "Skill 运行时：向智能体提供只读共享 Skills 投影目录。",
 "backend/package/yuxi/agents/skills/remote_install.py": "远程 Skill 安装：在一次性沙盒中执行不可信的远程 Skill CLI，再投影为本地 Skill。",
 "backend/package/yuxi/agents/skills/buildin/mysql-reporter/scripts/_mysql_common.py": "MySQL 报表 Skill 公共库：连接与安全检查。",
 "backend/package/yuxi/agents/skills/buildin/mysql-reporter/scripts/describe_table.py": "MySQL describe table 脚本。",
 "backend/package/yuxi/agents/skills/buildin/mysql-reporter/scripts/list_tables.py": "MySQL 列表脚本。",
 "backend/package/yuxi/agents/skills/buildin/mysql-reporter/scripts/query.py": "MySQL 查询脚本（带超时与安全检查）。",
 "backend/package/yuxi/agents/toolkits/registry.py": "工具注册表：用装饰器给工具挂附加元数据。",
 "backend/package/yuxi/agents/toolkits/service.py": "工具服务：get_tool_metadata 获取工具元数据；resolve_configured_runtime_tools 把用户勾选的工具配置解析成真正可调用的工具实例列表。",
 "backend/package/yuxi/agents/toolkits/utils.py": "get_tool_info 工具信息辅助。",
 "backend/package/yuxi/agents/toolkits/buildin/tools.py": "内置工具集：联网搜索(Doubao/Tavily)、ocr_parse_file OCR 解析、present_artifacts 产物暴露、ask_user_question 追问用户。",
 "backend/package/yuxi/agents/toolkits/buildin/install_skill.py": "install_skill 工具：允许智能体在运行中安装 Skill。",
 "backend/package/yuxi/agents/toolkits/kbs/__init__.py": "知识库工具包：list_kbs / query_kb / find_kb_document / open_kb_document / get_mindmap 等，智能体的『查资料』能力来源。",
 "backend/package/yuxi/agents/toolkits/debug/__init__.py": "调试工具包。",
 "backend/package/yuxi/agents/callbacks/model_request_timing.py": "模型请求计时回调（首个模型请求时间点记录）。",
 "backend/package/yuxi/config/__init__.py": "路径与环境配置：get_user_data_dir / get_skill_data_dir / get_runtime_dir 等目录约定。",
 "backend/package/yuxi/knowledge/base.py": "知识库抽象基类、FileStatus 文件状态枚举、统一异常。",
 "backend/package/yuxi/knowledge/factory.py": "KnowledgeBaseFactory：按类型创建 Milvus/Dify/Notion 等知识库实例。",
 "backend/package/yuxi/knowledge/manager.py": "KnowledgeBaseManager：知识库实例管理。",
 "backend/package/yuxi/knowledge/runtime.py": "运行时知识库管理器入口（API/worker 共用）。",
 "backend/package/yuxi/knowledge/preview.py": "知识库文件预览：metadata + MinIO 原始对象读取 + Office→PDF 缓存。",
 "backend/package/yuxi/knowledge/schemas.py": "检索输入/输出 Schema。",
 "backend/package/yuxi/knowledge/read_models.py": "知识库只读模型。",
 "backend/package/yuxi/knowledge/cache.py": "知识库缓存。",
 "backend/package/yuxi/knowledge/parser/unified.py": "统一解析入口：按配置选择 OCR/文档解析器。",
 "backend/package/yuxi/knowledge/parser/mineru.py": "MinerU 文档解析器。",
 "backend/package/yuxi/knowledge/parser/mineru_official.py": "MinerU 官方 API 解析器。",
 "backend/package/yuxi/knowledge/parser/paddleocr_api.py": "PaddleOCR API 解析器。",
 "backend/package/yuxi/knowledge/parser/pp_structure_v3.py": "PP-StructureV3 版面解析。",
 "backend/package/yuxi/knowledge/parser/rapid_ocr.py": "RapidOCR 解析器。",
 "backend/package/yuxi/knowledge/parser/deepseek_ocr.py": "DeepSeek OCR 解析器。",
 "backend/package/yuxi/knowledge/parser/base.py": "解析器抽象基类。",
 "backend/package/yuxi/knowledge/parser/capabilities.py": "解析器能力声明。",
 "backend/package/yuxi/knowledge/parser/factory.py": "解析器工厂。",
 "backend/package/yuxi/knowledge/parser/zip_utils.py": "ZIP 包处理：MinerU 结果目录、图片链接替换。",
 "backend/package/yuxi/knowledge/chunking/ragflow_like/dispatcher.py": "分块分发器：chunk_file/chunk_markdown 按预设路由到具体解析器并组装 chunk 记录。",
 "backend/package/yuxi/knowledge/chunking/ragflow_like/nlp.py": "分块用 NLP 辅助（token 计数等）。",
 "backend/package/yuxi/knowledge/chunking/ragflow_like/presets.py": "分块预设：默认配置、参数归一化。",
 "backend/package/yuxi/knowledge/chunking/ragflow_like/parsers/book.py": "书籍类文档分块。",
 "backend/package/yuxi/knowledge/chunking/ragflow_like/parsers/general.py": "通用文档分块。",
 "backend/package/yuxi/knowledge/chunking/ragflow_like/parsers/laws.py": "法律法规类分块（条款感知）。",
 "backend/package/yuxi/knowledge/chunking/ragflow_like/parsers/qa.py": "QA 问答对分块。",
 "backend/package/yuxi/knowledge/chunking/ragflow_like/parsers/semantic.py": "语义分块（自动聚类）。",
 "backend/package/yuxi/knowledge/chunking/ragflow_like/parsers/separator.py": "分隔符分块（带 overlap）。",
 "backend/package/yuxi/knowledge/chunking/ragflow_like/utils/md_parser_utils.py": "Markdown 解析辅助：标题层级、表格块提取。",
 "backend/package/yuxi/knowledge/chunking/ragflow_like/utils/semantic_utils.py": "语义分块辅助：中英文分句、自动聚类。",
 "backend/package/yuxi/knowledge/chunking/ragflow_like/utils/table_utils.py": "HTML 表格转键值对。",
 "backend/package/yuxi/knowledge/eval/benchmark_generation.py": "评测数据集生成：从知识库 chunk 构造问题。",
 "backend/package/yuxi/knowledge/eval/evaluator.py": "评估器：检索命中、答案生成、指标聚合。",
 "backend/package/yuxi/knowledge/eval/service.py": "EvaluationService：RAG 评估编排（支持并发与断点续跑）。",
 "backend/package/yuxi/knowledge/graphs/milvus_graph_service.py": "MilvusGraphService：图谱构建与查询服务。",
 "backend/package/yuxi/knowledge/graphs/milvus_graph_vector_store.py": "MilvusGraphVectorStore：图实体/关系向量存储。",
 "backend/package/yuxi/knowledge/graphs/extractors/llm.py": "LLMGraphExtractor：用大模型从文本抽取实体和关系。",
 "backend/package/yuxi/knowledge/graphs/extractors/factory.py": "抽取器工厂。",
 "backend/package/yuxi/knowledge/graphs/extractors/base.py": "抽取器抽象基类。",
 "backend/package/yuxi/knowledge/graphs/graph_utils.py": "图谱工具函数。",
 "backend/package/yuxi/knowledge/implementations/milvus.py": "MilvusKB：生产级向量知识库实现（建集合、插入、检索）。",
 "backend/package/yuxi/knowledge/implementations/dify.py": "DifyKB：基于 Dify Dataset Retrieve API 的只读检索实现。",
 "backend/package/yuxi/knowledge/implementations/notion.py": "Notion 知识库实现。",
 "backend/package/yuxi/knowledge/implementations/read_only_connectors.py": "只读外部检索连接器基类。",
 "backend/package/yuxi/knowledge/utils/kb_utils.py": "知识库参数处理、内容哈希、元数据准备。",
 "backend/package/yuxi/knowledge/utils/url_fetcher.py": "URL 抓取（带私网 IP 防护）。",
 "backend/package/yuxi/models/chat.py": "对话模型适配：load_chat_model 按模型全名（provider/model）加载 OpenAI 兼容等后端；resolve_chat_model_spec 解析模型规格。",
 "backend/package/yuxi/models/embed.py": "Embedding 向量模型适配。",
 "backend/package/yuxi/models/rerank.py": "Rerank 重排模型适配。",
 "backend/package/yuxi/models/providers/service.py": "模型供应商服务：内置 Provider 初始化入 PostgreSQL，Redis 缓存提供一致视图。",
 "backend/package/yuxi/permissions/__init__.py": "权限常量与判断。",
 "backend/package/yuxi/permissions/resources.py": "资源权限定义。",
 "backend/package/yuxi/repositories/agent_repository.py": "AgentRepository：智能体 CRUD、可见性(share_config)与默认智能体 ensure_default_agent。",
 "backend/package/yuxi/repositories/agent_run_repository.py": "AgentRunRepository：AgentRun 行与租约的查询/更新。",
 "backend/package/yuxi/repositories/agent_run_request_repository.py": "AgentRunRequestRepository：排队请求行的查询与状态更新。",
 "backend/package/yuxi/repositories/agent_run_output_repository.py": "AgentRun 输出结果仓库。",
 "backend/package/yuxi/repositories/agent_state_repository.py": "智能体运行状态仓库。",
 "backend/package/yuxi/repositories/agent_env_repository.py": "智能体环境变量仓库。",
 "backend/package/yuxi/repositories/api_key_repository.py": "APIKeyRepository：API Key 的签发与校验。",
 "backend/package/yuxi/repositories/conversation_repository.py": "ConversationRepository：会话线程、消息、附件的读写。",
 "backend/package/yuxi/repositories/dashboard_repository.py": "仪表盘统计查询。",
 "backend/package/yuxi/repositories/department_repository.py": "部门仓库。",
 "backend/package/yuxi/repositories/evaluation_repository.py": "评估数据集/运行记录仓库。",
 "backend/package/yuxi/repositories/knowledge_base_repository.py": "KnowledgeBaseRepository：知识库元数据。",
 "backend/package/yuxi/repositories/knowledge_file_repository.py": "KnowledgeFileRepository：知识库文件记录与状态。",
 "backend/package/yuxi/repositories/knowledge_chunk_repository.py": "KnowledgeChunkRepository：分块记录。",
 "backend/package/yuxi/repositories/knowledge_graph_repository.py": "知识图谱持久化记录。",
 "backend/package/yuxi/repositories/model_message_audit_repository.py": "模型消息审计写入/查询。",
 "backend/package/yuxi/repositories/tool_message_audit_repository.py": "工具消息审计写入/查询。",
 "backend/package/yuxi/repositories/project_repository.py": "ProjectRepository：项目与 workdir 绑定。",
 "backend/package/yuxi/repositories/scheduled_agent_repository.py": "定时智能体任务定义与 occurrence。",
 "backend/package/yuxi/repositories/subagent_thread_repository.py": "子智能体线程父子关系。",
 "backend/package/yuxi/repositories/task_repository.py": "TaskRepository：Durable Task 行、租约、heartbeat。",
 "backend/package/yuxi/repositories/user_repository.py": "UserRepository：用户查找（支持 user_id/手机号登录标识）、锁定状态。",
 "backend/package/yuxi/services/agent_request_service.py": "消息提交用例：submit_agent_request 校验作用域→同一事务写用户消息+AgentRunRequest→检查活跃 Run 与 FIFO 队头→立即派发或排队。Web Chat / Agent Call / 评估入口共用。",
 "backend/package/yuxi/services/agent_request_queue_service.py": "线程级 FIFO 排队：dispatch_ready_head 派发队头、cancel/steer、stream_request_events 排队阶段 SSE、recover_pending_dispatches 恢复。",
 "backend/package/yuxi/services/agent_run_service.py": "Run 生命周期：创建 Run（prepare_agent_run_creation_scope 冻结配置快照→persist_agent_run_record→enqueue_agent_run）、查询/取消、stream_agent_run_events 把 Redis Stream 转成 SSE。",
 "backend/package/yuxi/services/agent_run_manifest_service.py": "AgentRun 执行清单固化（manifest + attempt 记录）。",
 "backend/package/yuxi/services/agent_config_service.py": "智能体配置写入准备 prepare_agent_config_write 与预置角色初始化 initialize_agent_presets。",
 "backend/package/yuxi/services/arq_worker.py": "run_worker()：装配 WorkerSettings 并启动 ARQ worker。",
 "backend/package/yuxi/services/run_worker.py": "Worker 执行核心（最长的服务文件）：process_agent_run 是 ARQ 任务的执行入口——抢占 Run 租约→心跳续租→固化 manifest→驱动 stream_agent_chat→把事件写 Redis Stream→终态写回 PG；并常驻运行过期租约/任务对账循环。",
 "backend/package/yuxi/services/run_queue_service.py": "Redis/ARQ 投递客户端：enqueue_run 把 run_id 推入执行队列。",
 "backend/package/yuxi/services/chat_service.py": "智能体执行编排：stream_agent_chat / stream_agent_resume 流式驱动智能体（解析 Agent 运行时、附件装配、Langfuse、逐事件产出、结果落库）。",
 "backend/package/yuxi/services/input_message_service.py": "输入消息标准化：build_chat_input_message / restore_chat_input_message。",
 "backend/package/yuxi/services/conversation_service.py": "会话服务：线程创建/列表/删除/搜索的视图组装。",
 "backend/package/yuxi/services/attachment_service.py": "附件服务：上传 MinIO、附件记录、artifact URL。",
 "backend/package/yuxi/services/artifact_service.py": "Artifact 产物服务：Run 产物文件登记与读取。",
 "backend/package/yuxi/services/subagent_run_service.py": "SubagentRunService：subagent_start 工具的后端——创建子 AgentRun（run_type=subagent）、维护父子线程关系。",
 "backend/package/yuxi/services/scheduled_agent_service.py": "定时智能体：任务定义、调度锁、到期触发复用 AgentRun 链路。",
 "backend/package/yuxi/services/task_service.py": "Durable Task 领域：Task/TaskContext、租约、进度、取消、终态。",
 "backend/package/yuxi/services/task_queue_service.py": "Durable Task 投递：ARQ 发布、pending 补发、失败收敛。",
 "backend/package/yuxi/services/task_registry.py": "任务注册表：task_type → 惰性加载的 Handler 定义（knowledge_ingest 等）。",
 "backend/package/yuxi/services/knowledge_task_service.py": "知识库后台任务 Handler：run_knowledge_ingest / run_knowledge_parse / run_knowledge_index / run_knowledge_graph。",
 "backend/package/yuxi/services/knowledge_folder_service.py": "知识库历史虚拟目录迁移编排。",
 "backend/package/yuxi/services/knowledge_dashboard_service.py": "知识域仪表盘统计。",
 "backend/package/yuxi/services/auth_service.py": "CLI 授权会话：创建/批准/换 Token。",
 "backend/package/yuxi/services/oidc_service.py": "OIDC 单点登录：发现、令牌交换、用户映射（最长的认证文件）。",
 "backend/package/yuxi/services/login_rate_limit_service.py": "登录限流：IP+账号 滑动窗口。",
 "backend/package/yuxi/services/user_identity_service.py": "用户标识：uid 生成、拼音转换、手机号校验。",
 "backend/package/yuxi/services/identity_admin_service.py": "管理员身份管理。",
 "backend/package/yuxi/services/memory_service.py": "用户长期记忆服务。",
 "backend/package/yuxi/services/mention_search_service.py": "@ 提及文件搜索。",
 "backend/package/yuxi/services/model_message_audit_service.py": "模型消息审计采集器（AIMessage 不进普通历史，单独审计）。",
 "backend/package/yuxi/services/tool_message_audit_service.py": "工具消息审计采集器。",
 "backend/package/yuxi/services/langfuse_service.py": "Langfuse 观测：trace 上下文构建与固化。",
 "backend/package/yuxi/services/dashboard_service.py": "仪表盘统计服务。",
 "backend/package/yuxi/services/feedback_service.py": "消息反馈。",
 "backend/package/yuxi/services/file_preview.py": "文件预览服务入口。",
 "backend/package/yuxi/services/context_compression_service.py": "上下文压缩服务。",
 "backend/package/yuxi/services/ocr_service.py": "OCR 配置中心与解析服务。",
 "backend/package/yuxi/services/operation_log_service.py": "log_operation 操作日志。",
 "backend/package/yuxi/services/project_service.py": "项目服务：implicit / managed / linked 三类项目创建。",
 "backend/package/yuxi/services/workdir_service.py": "Workdir 绑定解析：把 Conversation→Project→宿主目录。",
 "backend/package/yuxi/services/workspace_service.py": "个人工作区服务：文件树、搜索、读写。",
 "backend/package/yuxi/services/viewer_filesystem_service.py": "工作台文件系统视图服务（viewer）。",
 "backend/package/yuxi/services/channel_command_service.py": "外部通道命令服务。",
 "backend/package/yuxi/services/readiness_service.py": "启动就绪状态检查。",
 "backend/package/yuxi/storage/postgres/manager.py": "pg_manager：业务连接池 + LangGraph checkpoint 连接池 + Schema 版本校验。",
 "backend/package/yuxi/storage/postgres/models_business.py": "业务表 SQLAlchemy 模型：User/Agent/Conversation/Message/AgentRunRequest/AgentRun/Task/APIKey/Project/ScheduledAgent/审计表等。",
 "backend/package/yuxi/storage/postgres/models_knowledge.py": "知识域表模型：知识库/文件/分块/图谱/评估。",
 "backend/package/yuxi/storage/redis/manager.py": "Redis 客户端管理：同步/异步客户端、ARQ 连接参数。",
 "backend/package/yuxi/storage/minio/manager.py": "MinIO 客户端：对象上传/下载/临时访问。",
 "backend/package/yuxi/storage/neo4j/manager.py": "Neo4jConnectionManager：共享驱动与生命周期。",
 "backend/package/yuxi/utils/auth_utils.py": "AuthUtils：hash_password/verify_password(bcrypt)、create_access_token/verify_access_token(JWT)。",
 "backend/package/yuxi/utils/hash_utils.py": "哈希工具：hashstr、subagent_child_thread_id 子线程 ID 生成。",
 "backend/package/yuxi/utils/logging_config.py": "日志配置：标准 logging 桥接 loguru。",
 "backend/package/yuxi/utils/paths.py": "安全文件原语：open_directory_fd / open_regular_file_fd / ensure_within_root（no-follow 防路径逃逸）。",
 "backend/package/yuxi/utils/singleton.py": "SingletonMeta 单例元类。",
 "backend/package/yuxi/utils/thread_utils.py": "extract_thread_id 等线程工具。",
 "backend/package/yuxi/utils/upload_utils.py": "上传处理：write_upload_to_buffer / read_upload_with_limit。",
 "backend/package/yuxi/utils/filepreview.py": "文件预览原语：格式识别、文本渲染、Office 转换（不依赖 HTTP/存储）。",
 "backend/package/yuxi/utils/datetime_utils.py": "utc_now_naive 等时间工具。",
 "backend/package/yuxi/workspace/paths.py": "工作区路径：uid→目录映射、projects/<managed-name> 命名、normalize_workdir_path。",
 "backend/package/yuxi/workspace/filesystem.py": "no-follow 安全文件系统原语（唯一拥有宿主路径访问的模块）。",
 "backend/package/yuxi/workspace/workdir.py": "以 Project 为根的持久化 Workdir 视图。",
 "backend/package/yuxi/workspace/preview.py": "用户工作区文件预览与 Office→PDF 本地缓存。",
 "backend/package/yuxi/workspace/audit.py": "工作区审计。",
 "backend/scripts/seed_initial_users.py": "初始化种子用户/部门脚本。",
}

CORE_FILES = {
 "backend/server/main.py","backend/server/routers/agent_router.py","backend/server/routers/auth_router.py","backend/server/routers/knowledge_router.py","backend/server/routers/chat_router.py",
 "backend/server/utils/auth_middleware.py","backend/server/utils/lifespan.py",
 "backend/package/yuxi/services/agent_request_service.py","backend/package/yuxi/services/agent_request_queue_service.py",
 "backend/package/yuxi/services/agent_run_service.py","backend/package/yuxi/services/chat_service.py",
 "backend/package/yuxi/services/run_worker.py","backend/package/yuxi/services/run_queue_service.py",
 "backend/package/yuxi/services/input_message_service.py","backend/package/yuxi/services/knowledge_task_service.py",
 "backend/package/yuxi/services/subagent_run_service.py","backend/package/yuxi/services/task_registry.py",
 "backend/package/yuxi/agents/base.py","backend/package/yuxi/agents/buildin/chatbot/graph.py",
 "backend/package/yuxi/agents/toolkits/service.py","backend/package/yuxi/models/chat.py",
 "backend/package/yuxi/utils/auth_utils.py","backend/package/yuxi/storage/postgres/manager.py",
}

DIR_DESCR_F = {
 "web/src": "前端源码根：main.js 挂载应用，App.vue 是根组件。",
 "web/src/apis": "后端接口封装边界：所有 HTTP 请求都在这里定义，复用 base.js 的鉴权与错误处理。",
 "web/src/components": "可复用界面组件（聊天、文件、图谱、仪表盘、扩展中心等）。",
 "web/src/components/common": "通用基础组件（Markdown 渲染、PDF 预览、JSON 树等）。",
 "web/src/components/ToolCallingResult": "工具调用结果的渲染框架：按工具名分发到具体渲染组件。",
 "web/src/components/ToolCallingResult/tools": "每种工具一个渲染组件：读文件/写文件/搜索/知识库/MySQL/Web 搜索/子任务……",
 "web/src/components/dashboard": "仪表盘子组件。",
 "web/src/components/evaluation": "评估组件。",
 "web/src/components/extensions": "扩展中心组件（MCP/Skill/工具）。",
 "web/src/components/knowledge": "知识库组件。",
 "web/src/components/modals": "通用弹窗。",
 "web/src/components/model-management": "智能体与模型管理组件。",
 "web/src/components/scheduled-agents": "定时智能体组件。",
 "web/src/components/shared": "共享布局组件。",
 "web/src/components/sources": "引用来源组件（知识库分块、Web 搜索结果）。",
 "web/src/components/workspace": "工作区组件。",
 "web/src/composables": "组合式逻辑：请求排队、Run SSE、流式消息、审批、子任务等可复用逻辑。",
 "web/src/layouts": "页面布局（AppLayout / BlankLayout）。",
 "web/src/router": "路由与守卫：公开页、登录、/agent 主工作区、管理员页。",
 "web/src/stores": "Pinia 状态仓库：用户、智能体、线程、配置等跨页面状态。",
 "web/src/utils": "轻量工具函数：消息处理、Markdown、时间、审批、断线恢复等。",
 "web/src/views": "页面级入口组件。",
}

FILE_DESCR_F = {
 "web/src/main.js": "前端入口：创建 Vue 应用、挂载 Pinia(持久化)、路由、Ant Design Vue，预加载站点配置后 mount。",
 "web/src/App.vue": "根组件：承载路由出口。",
 "web/src/router/index.js": "路由表与守卫：/（公开首页）、/login、/agent（主工作区）、/workspace、/dashboard(超管)、/agent-manage、/extensions；requiresAuth 守卫 + 管理员守卫。",
 "web/src/layouts/AppLayout.vue": "登录后的应用布局（侧边导航）。",
 "web/src/layouts/BlankLayout.vue": "空白布局（公开页用）。",
 "web/src/apis/base.js": "统一请求封装：apiGet/apiPost/apiPut/apiDelete/apiRequest，自动带 Token、401 跳登录、统一错误提示；SSE fetch 也复用这里的鉴权。",
 "web/src/apis/index.js": "API 模块汇总导出（export * 自各业务模块 + base 的请求函数）。",
 "web/src/apis/agent_api.js": "智能体 API：createAgentRun(POST /api/agent/runs 发消息)、getAgents、generateTitle(自动起标题)、multimodalApi(多模态上传)、threadApi(线程)。",
 "web/src/apis/auth_api.js": "认证 API：登录、用户信息、OIDC、CLI 授权。",
 "web/src/apis/apikey_api.js": "API Key 管理 API。",
 "web/src/apis/agent_env_api.js": "智能体环境变量 API。",
 "web/src/apis/dashboard_api.js": "仪表盘统计 API。",
 "web/src/apis/department_api.js": "部门管理 API。",
 "web/src/apis/graph_api.js": "知识图谱 API。",
 "web/src/apis/knowledge_api.js": "知识库 API：知识库 CRUD、文档上传/解析、检索、评估。",
 "web/src/apis/mcp_api.js": "MCP 管理 API。",
 "web/src/apis/mention_api.js": "@ 提及搜索 API。",
 "web/src/apis/project_api.js": "项目 API。",
 "web/src/apis/scheduled_agent_api.js": "定时智能体 API。",
 "web/src/apis/skill_api.js": "Skills API。",
 "web/src/apis/system_api.js": "系统信息/配置 API。",
 "web/src/apis/tasker.js": "任务中心 API。",
 "web/src/apis/tool_api.js": "工具 API。",
 "web/src/apis/user_api.js": "用户 API。",
 "web/src/apis/user_config_api.js": "用户配置 API。",
 "web/src/apis/viewer_filesystem.js": "工作台文件视图 API。",
 "web/src/apis/workspace_api.js": "个人工作区 API。",
 "web/src/stores/user.js": "用户状态：Token、登录态、角色与 checkAdminPermission/checkSuperAdminPermission 权限判断。",
 "web/src/stores/agent.js": "当前智能体与运行配置状态。",
 "web/src/stores/chatThreads.js": "会话线程列表状态（增删改、标题）。",
 "web/src/stores/chatUI.js": "聊天界面状态。",
 "web/src/stores/config.js": "系统配置状态。",
 "web/src/stores/database.js": "知识库状态。",
 "web/src/stores/info.js": "站点信息状态。",
 "web/src/stores/projects.js": "项目状态。",
 "web/src/stores/tasker.js": "任务中心状态。",
 "web/src/stores/theme.js": "主题状态。",
 "web/src/composables/useAgentRequestQueue.js": "排队阶段：提交请求后订阅 Request SSE(startRequestStream)，拿到 run_id 再切到 Run SSE；处理排队/拒绝/steer。",
 "web/src/composables/useAgentRunStream.js": "Run SSE 消费：processRunSseResponse 手写 SSE 解析器、dispatchRunEventChunks 分发事件、断线按 Last-Event-ID 恢复。",
 "web/src/composables/useAgentStreamHandler.js": "流式事件 → 消息列表的状态更新处理器。",
 "web/src/composables/useStreamSmoother.js": "打字机平滑：把高频 token 块平滑地逐段展示。",
 "web/src/composables/useAgentThreadState.js": "每个线程的运行状态（是否流式中、排队队列）管理。",
 "web/src/composables/useApproval.js": "工具审批 / 追问用户的弹窗状态与提交。",
 "web/src/composables/useSubagentRuns.js": "子智能体 Run 的订阅与展示。",
 "web/src/composables/useAgentMentionConfig.js": "@ 提及的配置与解析。",
 "web/src/composables/useModelStatus.js": "模型可用状态轮询。",
 "web/src/composables/useGraph.js": "知识图谱数据获取。",
 "web/src/composables/useChunkPresetOptions.js": "分块预设选项。",
 "web/src/composables/useOutsidePointerdown.js": "点击外部关闭的组合式工具。",
 "web/src/views/HomeView.vue": "公开首页：产品介绍与登录入口。",
 "web/src/views/LoginView.vue": "登录页：账号密码 / OIDC 单点登录。",
 "web/src/views/OIDCCallbackView.vue": "OIDC 登录回调页：换 Token 后跳转。",
 "web/src/views/CLIAuthAuthorizeView.vue": "CLI 浏览器授权确认页。",
 "web/src/views/AgentView.vue": "智能体对话主页面：组合 AgentChatComponent（聊天）与 AgentPanel（配置/调试）。",
 "web/src/views/WorkspaceView.vue": "个人工作区页面：文件树、编辑与预览。",
 "web/src/views/DashboardView.vue": "管理员仪表盘。",
 "web/src/views/AgentManageView.vue": "智能体管理页。",
 "web/src/views/ExtensionsView.vue": "扩展中心：知识库 / 工具 / MCP / Skills。",
 "web/src/views/DataBaseView.vue": "知识库列表页。",
 "web/src/views/DataBaseInfoView.vue": "知识库详情页：文件列表、解析状态、分块、图谱、评估。",
 "web/src/views/EvaluationBenchmarkDetailView.vue": "评估数据集详情页。",
 "web/src/views/ScheduledAgentsView.vue": "定时智能体管理页。",
 "web/src/views/EmptyView.vue": "空状态占位页。",
 "web/src/components/AgentChatComponent.vue": "聊天核心组件（5600+ 行）：handleSendMessage 发送消息、乐观插入用户消息、消费 SSE 更新 AI 消息、排队展示、审批弹窗、重发/停止等全部交互。",
 "web/src/components/AgentPanel.vue": "智能体侧栏：运行配置、状态面板、调试信息组合。",
 "web/src/components/AgentInputArea.vue": "输入区：文本框、发送按钮、附件、模型选择组合。",
 "web/src/components/MessageInputComponent.vue": "消息输入组件：@ 提及、图片粘贴、草稿。",
 "web/src/components/AiTextarea.vue": "自适应高度输入框。",
 "web/src/components/AgentMessageComponent.vue": "单条消息渲染。",
 "web/src/components/ThreadMessageList.vue": "消息列表容器（滚动、虚拟化）。",
 "web/src/components/ReasoningBlockComponent.vue": "思考过程(Reasoning)渲染块。",
 "web/src/components/ToolCallsGroupComponent.vue": "工具调用组渲染。",
 "web/src/components/HumanApprovalModal.vue": "人工审批 / 追问用户弹窗。",
 "web/src/components/SubagentThreadView.vue": "子智能体线程视图。",
 "web/src/components/ConversationNavSection.vue": "会话导航分组区。",
 "web/src/components/ConversationNavItem.vue": "会话导航单项。",
 "web/src/components/ConversationProcessGroupComponent.vue": "会话进行中分组组件。",
 "web/src/components/DebugComponent.vue": "调试面板：状态、事件流查看。",
 "web/src/components/MessageDebugPanel.vue": "消息调试面板（审计时间线合并）。",
 "web/src/components/ContextUsageRing.vue": "上下文占用环形图。",
 "web/src/components/ModelSelectorComponent.vue": "模型选择器。",
 "web/src/components/ToolApprovalModeSelector.vue": "工具审批模式选择器。",
 "web/src/components/AgentArtifactsCard.vue": "Run 产物(artifacts)卡片。",
 "web/src/components/AgentFilePreview.vue": "智能体文件预览。",
 "web/src/components/AgentRuntimeConfigForm.vue": "智能体运行时配置表单。",
 "web/src/components/AgentEnvSettingsCard.vue": "智能体环境变量卡片。",
 "web/src/components/AttachmentOptionsComponent.vue": "附件选项组件。",
 "web/src/components/AttachmentTmpUploadModal.vue": "临时附件上传弹窗。",
 "web/src/components/GlobalSearchModal.vue": "全局搜索弹窗。",
 "web/src/components/FileUploadModal.vue": "知识库文件上传弹窗。",
 "web/src/components/FileTable.vue": "知识库文件表格（解析/入库状态、重试）。",
 "web/src/components/FileDetailModal.vue": "文件详情弹窗。",
 "web/src/components/FileTreeComponent.vue": "文件树组件。",
 "web/src/components/GraphCanvas.vue": "知识图谱画布。",
 "web/src/components/GraphDetailPanel.vue": "图谱详情面板。",
 "web/src/components/MindMapSection.vue": "思维导图区。",
 "web/src/components/KnowledgeGraphSection.vue": "知识图谱区。",
 "web/src/components/KnowledgeSourceSection.vue": "知识来源区。",
 "web/src/components/WebSearchSourceSection.vue": "Web 搜索来源区。",
 "web/src/components/SearchConfigPanel.vue": "检索配置面板。",
 "web/src/components/QuerySection.vue": "知识库检索测试区。",
 "web/src/components/ChunkParamsConfig.vue": "分块参数配置。",
 "web/src/components/EmbeddingModelSelector.vue": "向量模型选择器。",
 "web/src/components/RerankModelSelector.vue": "重排模型选择器。",
 "web/src/components/OCRSelector.vue": "OCR 引擎选择器。",
 "web/src/components/OCRSettingsSection.vue": "OCR 配置区。",
 "web/src/components/SkillSettingsSection.vue": "Skill 配置区。",
 "web/src/components/ProjectSelectionSection.vue": "项目选择区。",
 "web/src/components/BasicSettingsSection.vue": "基础设置区。",
 "web/src/components/ShareConfigForm.vue": "分享配置表单。",
 "web/src/components/SettingsModal.vue": "设置弹窗。",
 "web/src/components/AccountSettingsComponent.vue": "账户设置。",
 "web/src/components/ApiKeyManagementComponent.vue": "API Key 管理组件。",
 "web/src/components/UserManagementComponent.vue": "用户管理组件（管理员）。",
 "web/src/components/UserInfoComponent.vue": "用户信息组件。",
 "web/src/components/UserConfigSettingsCard.vue": "用户配置卡片。",
 "web/src/components/DepartmentManagementComponent.vue": "部门管理组件。",
 "web/src/components/TaskCenterDrawer.vue": "任务中心抽屉。",
 "web/src/components/WorkspacePathPicker.vue": "工作区路径选择器。",
 "web/src/components/RefsComponent.vue": "引用来源组件。",
 "web/src/components/ImagePreviewComponent.vue": "图片预览组件。",
 "web/src/components/McpEnvEditor.vue": "MCP 环境变量编辑器。",
 "web/src/components/common/MarkdownPreview.vue": "Markdown 渲染组件（代码高亮、表格、图片）。",
 "web/src/components/common/PdfPreview.vue": "PDF 预览组件。",
 "web/src/components/common/JsonTreeViewer.vue": "JSON 树查看器。",
 "web/src/components/common/JsonTreeNode.vue": "JSON 树节点。",
 "web/src/components/common/FileBrowserTable.vue": "文件浏览表格。",
 "web/src/components/common/FileTypeIcon.vue": "文件类型图标。",
 "web/src/components/common/MentionTextRenderer.vue": "@ 提及文本渲染。",
 "web/src/components/common/CollapseTransition.vue": "折叠过渡动画。",
 "web/src/components/common/ActionDropdown.vue": "操作下拉菜单。",
 "web/src/components/common/ActionTrigger.vue": "操作触发按钮。",
 "web/src/components/common/FallbackAvatar.vue": "头像缺省组件。",
 "web/src/components/ToolCallingResult/ToolCallRenderer.vue": "工具调用渲染分发器：按工具名路由到 tools/ 下对应组件。",
 "web/src/components/ToolCallingResult/toolRegistry.js": "工具名 → 渲染组件的注册表。",
 "web/src/utils/messageProcessor.js": "消息处理器：把后端消息/chunk 转成渲染结构。",
 "web/src/utils/messageGrouping.js": "消息分组（工具调用与 AI 消息的归组）。",
 "web/src/utils/conversationProcessGrouping.js": "会话进行中分组。",
 "web/src/utils/messageDebug.js": "消息调试数据合并。",
 "web/src/utils/runStreamResume.js": "Run SSE 断线恢复：seq 比较、Last-Event-ID 解析。",
 "web/src/utils/toolApproval.js": "审批相关工具函数。",
 "web/src/utils/errorHandler.js": "统一错误处理。",
 "web/src/utils/markdown_preview.js": "Markdown 渲染工具。",
 "web/src/utils/htmlPreviewRenderer.js": "HTML 预览渲染。",
 "web/src/utils/file_preview.js": "文件预览工具。",
 "web/src/utils/time.js": "时间格式化。",
 "web/src/utils/scrollController.js": "滚动控制器（跟随最新消息）。",
 "web/src/utils/agentConfigUtils.js": "智能体配置工具。",
 "web/src/utils/contextUsage.js": "上下文占用计算。",
 "web/src/utils/runTiming.js": "Run 阶段耗时展示。",
 "web/src/utils/oidcAutoStart.js": "OIDC 自动登录与回跳清理。",
 "web/src/utils/thread_draft.js": "新会话草稿。",
 "web/src/utils/threadCreation.js": "线程创建工具。",
 "web/src/utils/subagentThread.js": "子智能体线程工具。",
 "web/src/utils/subagentRuns.js": "子智能体 Run 工具。",
 "web/src/utils/mention_utils.js": "@ 提及工具。",
 "web/src/utils/modelMetadata.js": "模型元数据。",
 "web/src/utils/questionUtils.js": "追问(ask_user_question)工具。",
 "web/src/utils/singleFlight.js": "单飞请求（去重并发）。",
 "web/src/utils/kb_utils.js": "知识库工具。",
 "web/src/utils/knowledge_file_policy.js": "知识文件策略。",
 "web/src/utils/file_utils.js": "文件工具。",
 "web/src/utils/passwordValidation.js": "密码强度校验。",
 "web/src/utils/pixelAvatar.js": "像素头像生成。",
 "web/src/utils/upload_limits.js": "上传大小限制。",
 "web/src/utils/agentRun.js": "Run 状态判断（isSteerableMainChatRun 等）。",
}

CORE_FILES_F = {
 "web/src/main.js","web/src/router/index.js","web/src/apis/base.js","web/src/apis/agent_api.js",
 "web/src/components/AgentChatComponent.vue","web/src/views/AgentView.vue",
 "web/src/composables/useAgentRequestQueue.js","web/src/composables/useAgentRunStream.js",
 "web/src/composables/useAgentStreamHandler.js","web/src/stores/user.js",
 "web/src/components/ToolCallingResult/ToolCallRenderer.vue","web/src/views/LoginView.vue",
 "web/src/components/MessageInputComponent.vue","web/src/components/HumanApprovalModal.vue",
}
